[package]
name = "algo-rust"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "search_benchmark"
path = "benches/search_benchmark.rs"
harness = false

[dev-dependencies]
criterion = "0.5"

[dependencies]
